### ISSUE TITLE
Crashes app

### ISSUE THREAD

**Issue by Maliffic** [TenkaiRuri/flutter_video_compress#1]
On compress video the app just crashes.

E/flutter (16713): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/att.moe.fluttervediocompressexample-gbpmaA3AowDifB_AlSEofw==/base.apk"],nativeLibraryDirectories=[/data/app/att.moe.fluttervediocompressexample-gbpmaA3AowDifB_AlSEofw==/lib/x86, /data/app/att.moe.fluttervediocompressexample-gbpmaA3AowDifB_AlSEofw==/base.apk!/lib/x86, /system/lib]]] couldn't find "libpldroid_shortvideo_core.so"
E/flutter (16713): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
E/flutter (16713): 	at java.lang.System.loadLibrary(System.java:1669)
E/flutter (16713): 	at com.qiniu.pili.droid.shortvideo.b.l.<clinit>(ShortVideoCore.java:32)
E/flutter (16713): 	at com.qiniu.pili.droid.shortvideo.b.l.a(ShortVideoCore.java:14)
E/flutter (16713): 	at com.qiniu.pili.droid.shortvideo.b.p.<init>(ShortVideoTranscoderCore.java:157)
E/flutter (16713): 	at com.qiniu.pili.droid.shortvideo.PLShortVideoTranscoder.<init>(PLShortVideoTranscoder.java:18)

**Comment by TenkaiRuri** [comment]
This seems to be a problem with the x86 platform.
For this I have added support for x86.
This problem is solved, now the package name is called [flutter_video_compress](https://pub.dartlang.org/packages/flutter_video_compress), if you have any questions, you can open this issue again, thank you for the issue.
