### ISSUE TITLE
[Suggestion] Rename methods

### ISSUE THREAD

**Issue by GustavoContreiras** [TenkaiRuri/flutter_video_compress#29]
I saw that you owners are not americans and maybe thats the reason the methods don't have a intuitive name.

My suggestions for rename:
startCompress -> compressVideo
convertVideoToGif -> compressVideoToGif
stopCompress -> cancelCompress
getThumbnail -> getThumbnailBytesList
getThumbnailWithFile -> getThumbnail

**Comment by TenkaiRuri** [comment]
`convertVideoToGif` Maybe should ask his opinion @vlada3003

**Comment by vlada3003** [comment]
Conversion of video to gif won't do any compression of the video, that's why I have chosen the method name.
I agree with other suggestions with just a couple  observations. cancelCompress should be cancelCompression. Renaming to an existing method name might be confusing to existing library users, maybe getThumbnailFile would be more appropriate?

**Comment by GustavoContreiras** [comment]
I don't know how its working on backend, but as an user of the package, converting to gif looks like a compression cause it uses the compressProgress stream.

So maybe it should have a convertingProgress stream and a isConverting boolean.

And yeah, maybe getThumbnailFile is more appropriate.
